FROM $BASE_IMAGE
USER root

RUN git clone https://github.com/pgbouncer/pgbouncer.git && \
    cd pgbouncer && \
    git checkout -b "$PGB_GITHUB_BRANCH" tags/pgbouncer_1_24_1 && \
    cd .. && \
    git clone https://github.com/awslabs/pgbouncer-fast-switchover.git --branch "ci-build" && \
    cd pgbouncer-fast-switchover && \
    ./install-pgbouncer-rr-patch.sh ../pgbouncer && \
    cd ../pgbouncer && \
    git submodule init && \
    git submodule update && \
    ./autogen.sh && \
    ln -s "/usr/bin/$ARCH-amazon-linux-gnu-pkg-config" "/usr/bin/$ARCH-redhat-linux-gnu-pkg-config" && \
    ./configure --prefix=/usr/local --exec-prefix=/usr/bin && \
    make && \
    make install

RUN cp /home/pgbouncer/pgbouncer/pgbouncer /usr/local/bin/

USER pgbouncer
WORKDIR /home/pgbouncer

COPY ./start.sh /start.sh
COPY ./pub_metrics.sh /pub_metrics.sh
COPY ./adaptivepgbouncer.sh /adaptivepgbouncer.sh

COPY ./routing_rules.py /home/pgbouncer/

# The Deployment's preStop hook runs ./pre-stop.sh from /home/pgbouncer to
# gracefully drain connections before shutdown. Without this COPY the hook
# fails (FailedPreStopHook) and pgbouncer is hard-killed (SIGTERM), severing
# live client connections.
COPY ./pre-stop.sh /home/pgbouncer/pre-stop.sh

#ENTRYPOINT ["/bin/bash", "/start.sh"]
